### ISSUE TITLE
More `dapp help`

### ISSUE THREAD

**Issue by ryepdx** [dapphub/dapp#34] opened 2017-07-17 16:25 UTC
It'd be nice if `dapp` could give the the user some idea of how to use it. Right now `dapp help` just prints

```
Usage: dapp <command> [<args>...]
```

Having something more in line with `git help` would be nice.

**Comment by dbrock** [comment] 2017-12-11 09:00
Duplicate of #31

**Closed by dbrock** 2017-12-11 09:00 UTC
